from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class Lead(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100), nullable=False)
    telefone = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(100))
    origem = db.Column(db.String(50), default='manual')
    status = db.Column(db.String(30), default='novo')
    interesse = db.Column(db.String(50))
    observacoes = db.Column(db.Text)
    criado_em = db.Column(db.DateTime, default=datetime.utcnow)
    atualizado_em = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    interacoes = db.relationship('Interacao', backref='lead', lazy=True, cascade='all, delete-orphan')

class Interacao(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    lead_id = db.Column(db.Integer, db.ForeignKey('lead.id'), nullable=False)
    tipo = db.Column(db.String(30), nullable=False)
    descricao = db.Column(db.Text)
    data = db.Column(db.DateTime, default=datetime.utcnow)

class Matricula(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    imovel_endereco = db.Column(db.String(200), nullable=False)
    cartorio = db.Column(db.String(100))
    numero_matricula = db.Column(db.String(50))
    proprietario_nome = db.Column(db.String(100))
    proprietario_contato = db.Column(db.String(100))
    area = db.Column(db.String(50))
    valor = db.Column(db.String(50))
    situacao = db.Column(db.String(30), default='pendente')
    observacoes = db.Column(db.Text)
    consulta_data = db.Column(db.DateTime, default=datetime.utcnow)
    followup_data = db.Column(db.DateTime)
    documentos = db.Column(db.Text)

class AnuncioPortal(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    portal = db.Column(db.String(50), nullable=False)
    titulo = db.Column(db.String(200), nullable=False)
    endereco = db.Column(db.String(200))
    preco = db.Column(db.String(50))
    area = db.Column(db.String(50))
    quartos = db.Column(db.String(20))
    telefone = db.Column(db.String(50))
    url = db.Column(db.Text)
    contato_nome = db.Column(db.String(100))
    foto_url = db.Column(db.Text)
    importado_em = db.Column(db.DateTime, default=datetime.utcnow)
    convertido_lead_id = db.Column(db.Integer, db.ForeignKey('lead.id'))
    convertido_lead = db.relationship('Lead', backref='anuncio_origem')

class Imovel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(200), nullable=False)
    tipo = db.Column(db.String(30))
    negocio = db.Column(db.String(20))
    endereco = db.Column(db.String(200), nullable=False)
    bairro = db.Column(db.String(100))
    cidade = db.Column(db.String(100), default='Assis-SP')
    cep = db.Column(db.String(20))
    preco = db.Column(db.String(50))
    area = db.Column(db.String(50))
    quartos = db.Column(db.String(20))
    banheiros = db.Column(db.String(20))
    vagas = db.Column(db.String(20))
    descricao = db.Column(db.Text)
    proprietario_nome = db.Column(db.String(100))
    proprietario_telefone = db.Column(db.String(50))
    proprietario_email = db.Column(db.String(100))
    foto_capa = db.Column(db.String(200))
    status = db.Column(db.String(30), default='ativo')
    visualizacoes = db.Column(db.Integer, default=0)
    destaque = db.Column(db.Boolean, default=False)
    criado_em = db.Column(db.DateTime, default=datetime.utcnow)
    fotos = db.relationship('ImovelFoto', backref='imovel', lazy=True, cascade='all, delete-orphan')

class ImovelFoto(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    imovel_id = db.Column(db.Integer, db.ForeignKey('imovel.id'), nullable=False)
    caminho = db.Column(db.String(200), nullable=False)
    ordem = db.Column(db.Integer, default=0)
    criada_em = db.Column(db.DateTime, default=datetime.utcnow)

class Lembrete(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(200), nullable=False)
    cliente_nome = db.Column(db.String(100))
    cliente_telefone = db.Column(db.String(20))
    corretor_nome = db.Column(db.String(100), default='Andre Comelli')
    corretor_telefone = db.Column(db.String(20), default='(18) 99762-8360')
    imovel_id = db.Column(db.Integer, db.ForeignKey('imovel.id'))
    imovel = db.relationship('Imovel', backref='lembretes')
    data_visita = db.Column(db.DateTime, nullable=False)
    local = db.Column(db.String(200))
    observacoes = db.Column(db.Text)
    lembrado = db.Column(db.Boolean, default=False)
    criado_em = db.Column(db.DateTime, default=datetime.utcnow)
